console.clear();
console.log("=== READIFY DEBUG ===");
console.log("Page URL:", window.location.href);
console.log("Checking loaded resources:");
console.log("✓ bookData:", typeof bookData !== 'undefined' ? "LOADED" : "MISSING");
console.log("✓ setupGlobalLogin:", typeof setupGlobalLogin !== 'undefined' ? "LOADED" : "MISSING");
console.log("✓ setupQuotes:", typeof setupQuotes !== 'undefined' ? "LOADED" : "MISSING");
console.log("✓ toggleTheme:", typeof toggleTheme !== 'undefined' ? "LOADED" : "MISSING");
console.log("✓ DOM Elements:");
console.log("  - navLinks:", document.getElementById('navLinks') ? "✓" : "✗");
console.log("  - login-container:", document.getElementById('login-container') ? "✓" : "✗");
console.log("  - book-grid:", document.getElementById('book-grid') ? "✓" : "✗");
console.log("DOM Content Loaded:", document.readyState);
